#!/usr/bin/env bash
#
# Copyright 2020-2023 The WarpX Community
#
# License: BSD-3-Clause-LBNL
# Authors: Axel Huebl

set -eu -o pipefail

cd Docs

curl -L -o amrex-doxygen-web.tag.xml \
  https://amrex-codes.github.io/amrex/docs_xml/doxygen/amrex-doxygen-web.tag.xml

curl -L -o openpmd-api-doxygen-web.tag.xml \
  https://openpmd-api.readthedocs.io/en/latest/_static/doxyhtml/openpmd-api-doxygen-web.tag.xml

# Treat all warnings as errors
if ! grep -q "WARN_AS_ERROR = YES" Doxyfile; then
    # Add line with the comment
    echo "" >> Doxyfile
    echo "# Overwrite value of WARN_AS_ERROR" >> Doxyfile
    echo "WARN_AS_ERROR = YES" >> Doxyfile
fi

# Run doxygen
doxygen
